version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cyber-ai-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cyber_ai
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cyber-ai-network

  mongo-express:
    image: mongo-express:latest
    container_name: cyber-ai-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - cyber-ai-network

volumes:
  mongodb_data:

networks:
  cyber-ai-network:
    driver: bridge 